name: nvidia-core20
base: core20
adopt-info: nvidia
summary: nvidia and mesa libraries for core20 snaps
description: |
  An experimental content snap containing the nvidia and mesa libraries and drivers for core 20
compression: lzo
grade: stable
confinement: strict

architectures:
  - build-on: amd64

parts:
  nvidia:
    plugin: nil
    override-pull:
      snapcraftctl set-version `LANG=C apt-cache policy libnvidia-common-470-server | sed -rne 's/^\s+Candidate:\s+([^-]*)-.+$/\1/p'`
    stage-packages:
      - libgl1-mesa-dri
      - va-driver-all
      - libegl1
      - libgles2
      - libnvidia-egl-wayland1
      - libnvidia-cfg1-470-server
      - libnvidia-common-470-server
      - libnvidia-compute-470-server
      - libnvidia-decode-470-server
      - libnvidia-encode-470-server
      - libnvidia-extra-470-server
      - libnvidia-gl-470-server
      - libnvidia-fbc1-470-server
      - libnvidia-ifr1-470-server
    organize:
      'usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/dri/*': egl/dri/
      'usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/*.so*': egl/lib/
      'usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/vdpau/*.so*': egl/lib/vdpau/
      'usr/share/glvnd': egl/glvnd/
      'usr/share/libdrm': egl/libdrm/
      'usr/share/drirc.d/': egl/drirc.d/
      'etc/OpenCL': egl/OpenCL/
      'usr/share/vulkan': egl/vulkan/
      'usr/share/doc': doc/
    prime:
      - egl
      - doc

slots:
  graphics-core20:
    interface: content
    read:
      - egl
